import {
	faAngleUp,
	faAngleDown,
	faPlus,
	faMinus,
	faPen,
	faTrashCan,
	faFileArrowUp,
	faCircleChevronLeft,
	faCopy,
	faCheck,
	faPenToSquare,
	faFloppyDisk,
	faFilePdf,
	faUpload,
	faFilter,
	faEyeSlash,
	faEye,
	faTriangleExclamation,
	faRightFromBracket,
	faEnvelope,
	faSquarePollVertical,
	faListCheck,
	faSpinner,
} from '@fortawesome/free-solid-svg-icons';
import { faSquare, faSquareCheck, faCommentDots } from '@fortawesome/free-regular-svg-icons';

export const faIcons = [
	faAngleUp,
	faAngleDown,
	faPlus,
	faMinus,
	faPen,
	faTrashCan,
	faFileArrowUp,
	faCircleChevronLeft,
	faCopy,
	faCheck,
	faSquare,
	faSquareCheck,
	faCommentDots,
	faPenToSquare,
	faFloppyDisk,
	faFilePdf,
	faUpload,
	faFilter,
	faEyeSlash,
	faEye,
	faTriangleExclamation,
	faRightFromBracket,
	faEnvelope,
	faSquarePollVertical,
	faListCheck,
	faSpinner,
];
